name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Could you please tell us about the behavior you expect?

  - type: textarea
    id: other
    attributes:
      label: other
      description: About everything else.
