name: build_stable_sse

on:
  push:
    tags:
      - 'v*.*.*'

env:
  build-mode: Release # Release | Debug
  # Explicit cache location to cache only nuget dependencies for this project.
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]

    steps:
      # Ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#building-and-testing-your-code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: .NET Cache
        # If there is a cache here, it is restored, otherwise it is cached at the end.
        uses: actions/cache@v4
        with:
          # - Specify the same as `NUGET_PACKAGES`
          path: |
            ${{ github.workspace }}/.nuget/packages
            ${{ github.workspace }}/PandoraPlus/bin
            ${{ github.workspace }}/PandoraPlus/obj
            ${{ github.workspace }}/third_party/HKX2-Library/HKX2 WPF/bin
            ${{ github.workspace }}/third_party/HKX2-Library/HKX2 WPF/obj
            ${{ github.workspace }}/third_party/XML-Cake/XML Cake/bin
            ${{ github.workspace }}/third_party/XML-Cake/XML Cake/obj
          key: nuget-${{ runner.os }}-${{ matrix.dotnet-version }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Build
        run: dotnet build "./PandoraPlus.sln" --configuration ${{ env.build-mode }}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pandora.Behaviour.Engine
          path: |
            ./PandoraPlus/bin/${{ env.build-mode }}/net7.0-windows
            
      - name: Download
        uses: actions/download-artifact@v4
        with:
         name: Pandora.Behaviour.Engine
         path: ./
         merge-multiple: true
         
      - name: Zip Artifact For Deployment
        run: Compress-Archive -Path ./* -Destination ./Pandora_Behaviour_Engine.zip
         
      - name: Create Release
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
         gh release create "${{ github.ref }}"
         "./Pandora_Behaviour_Engine.zip"
         --generate-notes
         --title "Pandora Behaviour Engine ${{ github.ref }}"
    